Css canvas medical
daisyyoo/c0822-code-solutions pull request #21
Opened 2022-08-27 06:20 UTC by daisyyoo

![CSS Canvas Medical Gif](https://user-images.githubusercontent.com/103452411/187017763-64919f39-478c-46ef-b51d-7d5d6eb0c8f2.gif)

I got everything except for the 2 border lines that somehow would not show up on my screen. I have commented the css code where the border-bottom and color would go if it worked like I think it would. Please help me fix it and I will edit it so it can be perfected. Thank you.

2022-08-27 18:09 UTC, thebearingedge requested changes

2022-08-27 18:09 UTC, thebearingedge commented on css-canvas-medical/index.html
> +      <div class="header">
There is a `<header>` element you can use instead of a class of `"header"`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

2022-08-27 18:09 UTC, thebearingedge commented on css-canvas-medical/index.html
> +        <div class="header-nav">
There is a `<nav>` element that you can use.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

2022-08-27 18:09 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +}
Here is where you can add your bottom border. Lemme know if it doesn't work somehow.

https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom

2022-08-27 23:01 UTC, daisyyoo commented
![CSS Canvas Medical Gif](https://user-images.githubusercontent.com/103452411/187050826-bb9306c7-7c4a-4825-97f4-13f77b066f99.gif)

Thank you for the help! I fixed it. The Gif toward the end is where I'm comparing the solution side by side.

2022-08-28 00:44 UTC, thebearingedge approved these changes

2022-08-29 15:59 UTC, merged